postgress:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: pgadmin
      pass: thisIsASecurePassword33@
      dbname: master
      schema: public

    prod:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: pgadmin
      pass: thisIsASecurePassword33@
      dbname: master
      schema: public

