version: '3.7'

services:
  postgres:
    networks:
      - fi_network
    image: postgres
    container_name: fi_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data    
    restart: always
  pgadmin:
    networks:
      - fi_network  
    image: dpage/pgadmin4
    container_name: fi_pgadmin
    ports:
      - "5656:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
  dbt-postgres:
    networks:
      - fi_network  
    image: dbt-postgres
    build:
      context: ./
      dockerfile: Dockerfile-dbt
      target: dbt-postgres
    container_name: fi_dbt
    command: run
    depends_on: 
    - postgres
    volumes:
      - type: bind
        source: ./
        target: /usr/app
      - type: bind
        source: ./.dbt
        target: /root/.dbt/
  elt-cron:
    networks:
      - fi_network
    image: etl-cron
    build:
      context: ./
      dockerfile: Dockerfile-cron
    container_name: fi_etl_cron
    command: cron -f
    depends_on: 
    - dbt-postgres
    - postgres        
volumes:
  pgdata:
networks:
  fi_network:
    
