FROM ubuntu:20.04
RUN apt-get update && apt-get -y install cron
RUN apt-get install -y python3-pip
RUN pip3 install pandas
RUN pip3 install sodapy
RUN pip3 install sqlalchemy
RUN apt-get install -y python3-psycopg2
COPY getFireData.py /etc/cron.d/getFireData.py
COPY cron/root /etc/cron.d/root
#COPY cron/root  /var/spool/cron/crontabs/root
RUN chmod 0744 /etc/cron.d/getFireData.py
RUN chmod +x /etc/cron.d/root
RUN crontab /etc/cron.d/root
RUN touch /var/log/cron.log
#CMD cron -f
#CMD bash