version: '3.7'

services:
  postgres:
    image: postgres
    container_name: fi_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data    
    restart: always
    ports: 
      - "5432:5432"
    environment:
      DATABASE_HOST: "127.0.0.1"
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "thisIsASecurePassword33@"
      POSTGRES_DB: "master"
  pgadmin:
    image: dpage/pgadmin4
    container_name: fi_pgadmin
    ports:
      - "5656:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
  dbt-postgres:
    image: dbt-postgres
    container_name: fi_dbt
    command: run
    depends_on: 
    - postgres
    volumes:
      - type: bind
        source: ./
        target: /usr/app
      - type: bind
        source: ./.dbt
        target: /root/.dbt/
volumes:
  pgdata:
    
